[tox]
envlist = py310, py311
skipsdist = True

[testenv]
deps =
    -rrequirements.txt
    flake8

commands =
    flake8 .

setenv =
    PYTHONPATH = {toxinidir}

# Ambiente só para rodar o pipeline
[testenv:run]
deps =
    -rrequirements.txt

commands =
    python src/app.py